// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

// Load .env from project root
config({ path: resolve(__dirname, "../.env") });
// Also load backend/.env if it exists (takes precedence)
config();

// Use DIRECT_URL for migrations (bypasses PgBouncer connection pooler)
const DIRECT_URL = process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || "postgresql://postgres:postgres@localhost:5432/resume_analyzer";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DIRECT_URL,
  },
});
